<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(MSBuildThisFileDirectory)..\..\common\oni-mod.props" />

  <PropertyGroup>
    <AssemblyName>NoMagicFridges</AssemblyName>
    <RootNamespace>NoMagicFridges</RootNamespace>
    <Version>0.2.1</Version>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)..\..\common\oni-mod.targets" />

</Project>
